const english={navFeatures:'Features',navPrivacy:'Privacy',hero:'Quick Cart for Bandcamp',lead:'Add digital music to your Bandcamp cart at the minimum price.<br>Preview tracks and adjust prices before checkout.',store:'View on Chrome Web Store',release:'Version 2, including gift-card features, is being prepared for release. The store offers the currently published version.',reviewLabel:'Review before checkout',featuresTitle:'Features',featuresDesc:'Turn each feature on or off in settings.',tab0:'Add to cart',tab1:'Review your cart',tab2:'Add funds',tab3:'Settings',galleryNote:'Screens use fictional music and accounts for demonstration.',giftTitle:'Buy a gift card',giftDesc:'Choose Add funds from your cart to buy a gift card. After purchase, enter the code delivered to your email.',step1Title:'Choose an amount and buy',step1:'Bandcamp’s official checkout opens in a separate window. Your original cart stays open.',step2Title:'Enter the code from your email',step2:'Enter the delivered code and click Add to balance. An Open Gmail button takes you to your inbox.',step3Title:'Return with the updated balance',step3:'Once registration is confirmed, return to your cart. The official screen appears if additional verification is needed.',giftNote:'Registration currently supports JPY cards. Gmail is not connected and email is not read.',privacyTitle:'Privacy',privacyDesc:'Gmail is not connected and email is not read. Entered codes are sent to Bandcamp. Codes and card details are not saved, and codes are not sent to the developer.',privacyLink:'Privacy policy',unofficial:'An unofficial extension. Not affiliated with Bandcamp.',contact:'Contact & bug reports'};
const japanese=Object.fromEntries([...document.querySelectorAll('[data-key]')].map(node=>[node.dataset.key,node.innerHTML]));
const names=['01-minimum','02-review','03-gift','04-settings'];
let lang;try{lang=localStorage.getItem('language');}catch{}
if(!['ja','en'].includes(lang))lang=navigator.language.startsWith('ja')?'ja':'en';
let slide=0;
function showSlide(index){slide=index;document.querySelectorAll('[data-slide]').forEach(button=>{const active=Number(button.dataset.slide)===slide;button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;});const image=document.getElementById('feature-image');image.src=`assets/${lang}/${names[slide]}.png`;image.alt=(lang==='ja'?japanese:english)['tab'+slide];document.getElementById('feature-panel').setAttribute('aria-labelledby','tab-'+slide);}
function translate(){document.documentElement.lang=lang;document.querySelectorAll('[data-key]').forEach(node=>node.innerHTML=(lang==='ja'?japanese:english)[node.dataset.key]);document.getElementById('language').textContent=lang==='ja'?'English':'日本語';document.getElementById('language').setAttribute('aria-label',lang==='ja'?'Switch to English':'日本語に切り替え');document.getElementById('hero-image').src=`assets/review-${lang}.png`;document.getElementById('hero-image').alt=lang==='ja'?'購入前のカート確認画面':'Cart review before checkout';showSlide(slide);}
document.getElementById('language').addEventListener('click',()=>{lang=lang==='ja'?'en':'ja';try{localStorage.setItem('language',lang);}catch{}translate();});
document.querySelectorAll('[data-slide]').forEach(button=>{button.addEventListener('click',()=>showSlide(Number(button.dataset.slide)));button.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();showSlide(event.key==='Home'?0:event.key==='End'?3:(slide+(event.key==='ArrowRight'?1:3))%4);document.getElementById('tab-'+slide).focus();}});});
translate();
