const english={navFeatures:'Features',navPrivacy:'Privacy',eyebrow:'A CHROME EXTENSION FOR BANDCAMP',hero:'Found your next track?<br>Add it in one click.',lead:'Add music, preview tracks, check prices.<br>A few fewer steps before checkout.',store:'View on Chrome Web Store <span aria-hidden="true">↗</span>',release:'Version 2, including gift-card features, is being prepared for release. The store offers the currently published version.',reviewLabel:'Review before checkout',visualBottom:'More time for the music.',featuresEyebrow:'FEATURES',featuresTitle:'Your usual checkout.<br>Fewer steps.',featuresDesc:'Made for digital music on Bandcamp.<br>Choose the features you want to use.',tab0:'Add to cart',tab1:'Review your cart',tab2:'Add funds',tab3:'Settings',galleryNote:'Screens use fictional music and accounts for demonstration.',giftEyebrow:'NEW IN V2',giftTitle:'Add funds.<br>Keep your cart.',giftDesc:'Buy and register a gift card without losing your cart. Confirm your music purchase yourself at the end.',step1Title:'Choose an amount and buy',step1:'Bandcamp’s official checkout opens in a separate window. Your original cart stays open.',step2Title:'Enter the code from your email',step2:'Enter the delivered code and click Add to balance. An Open Gmail button takes you to your inbox.',step3Title:'Return with the updated balance',step3:'Once registration is confirmed, return to your cart. The official screen appears if additional verification is needed.',giftNote:'Registration currently supports JPY cards. Gmail is not connected and email is not read.',privacyTitle:'No mailbox access needed.',privacyDesc:'Enter the code yourself. It is sent to Bandcamp for registration. Card details, addresses and codes are not saved, and codes are not sent to the developer.',privacyLink:'Read the privacy policy →',closing:'Find your next favorite track.',unofficial:'An unofficial extension. Not affiliated with Bandcamp.',contact:'Contact & bug reports'};
const japanese=Object.fromEntries([...document.querySelectorAll('[data-key]')].map(node=>[node.dataset.key,node.innerHTML]));
const names=['01-minimum','02-review','03-gift','04-settings'];
let lang;try{lang=localStorage.getItem('language');}catch{}
if(!['ja','en'].includes(lang))lang=navigator.language.startsWith('ja')?'ja':'en';
let slide=0;
function showSlide(index){slide=index;document.querySelectorAll('[data-slide]').forEach(button=>{const active=Number(button.dataset.slide)===slide;button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;});const image=document.getElementById('feature-image');image.src=`assets/${lang}/${names[slide]}.png`;image.alt=(lang==='ja'?japanese:english)['tab'+slide];document.getElementById('feature-panel').setAttribute('aria-labelledby','tab-'+slide);}
function translate(){document.documentElement.lang=lang;document.querySelectorAll('[data-key]').forEach(node=>node.innerHTML=(lang==='ja'?japanese:english)[node.dataset.key]);document.getElementById('language').textContent=lang==='ja'?'English':'日本語';document.getElementById('language').setAttribute('aria-label',lang==='ja'?'Switch to English':'日本語に切り替え');document.getElementById('hero-image').src=`assets/review-${lang}.png`;document.getElementById('hero-image').alt=lang==='ja'?'購入前のカート確認画面':'Cart review before checkout';showSlide(slide);}
document.getElementById('language').addEventListener('click',()=>{lang=lang==='ja'?'en':'ja';try{localStorage.setItem('language',lang);}catch{}translate();});
document.querySelectorAll('[data-slide]').forEach(button=>{button.addEventListener('click',()=>showSlide(Number(button.dataset.slide)));button.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();showSlide(event.key==='Home'?0:event.key==='End'?3:(slide+(event.key==='ArrowRight'?1:3))%4);document.getElementById('tab-'+slide).focus();}});});
translate();
